import { NextRequest, NextResponse } from 'next/server'
import { createHmac, timingSafeEqual } from 'crypto'
import { createClient as createSupabaseAdmin } from '@supabase/supabase-js'

// GET /auth/wp?token=xxx
// Called by WordPress after user clicks "Lataa video" / "Hallinnoi videoitasi" link.
// Token is a HMAC-SHA256 signed payload generated by WordPress (ugcscroll.php).
// On success: creates/finds Supabase user, sets is_premium, redirects to dashboard.

export async function GET(req: NextRequest) {
  const origin = req.nextUrl.origin
  const loginUrl = new URL('/creator/login', origin)

  const token = req.nextUrl.searchParams.get('token')
  if (!token) return NextResponse.redirect(loginUrl)

  const secret = process.env.WP_JWT_SECRET
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!secret || !supabaseUrl || !serviceKey) {
    console.error('SSO: missing env vars')
    return NextResponse.redirect(loginUrl)
  }

  try {
    // ── 1. Verify token signature ──────────────────────────────────────────
    const dotIndex = token.lastIndexOf('.')
    if (dotIndex === -1) throw new Error('Invalid token format')

    const payloadB64 = token.slice(0, dotIndex)
    const sigB64 = token.slice(dotIndex + 1)

    const expectedSig = createHmac('sha256', secret).update(payloadB64).digest()
    let actualSig: Buffer
    try {
      actualSig = Buffer.from(sigB64, 'base64url')
    } catch {
      throw new Error('Invalid signature encoding')
    }

    if (
      expectedSig.length !== actualSig.length ||
      !timingSafeEqual(expectedSig, actualSig)
    ) {
      throw new Error('Invalid signature')
    }

    // ── 2. Parse and validate payload ─────────────────────────────────────
    const payload = JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8'))
    const { email, wp_user_id, is_premium, wp_post_id, name, age, city, bio } = payload

    if (!email || !wp_user_id) throw new Error('Missing email or wp_user_id')
    if (payload.exp < Math.floor(Date.now() / 1000)) throw new Error('Token expired')

    // ── 3. Find or create Supabase user via admin API ─────────────────────
    const admin = createSupabaseAdmin(supabaseUrl, serviceKey)

    // Generate magic link — creates user automatically if not yet registered
    const { data: linkData, error: linkError } = await admin.auth.admin.generateLink({
      type: 'magiclink',
      email: email.toLowerCase(),
      options: {
        redirectTo: `${origin}/creator/dashboard`,
      },
    })

    if (linkError || !linkData?.user) {
      throw new Error(`Magic link generation failed: ${linkError?.message}`)
    }

    const userId = linkData.user.id

    // ── 4. Upsert profile with WordPress data + premium status ────────────
    // KORJAUS: kirjoita is_premium (luotettu, allekirjoitettu token) AINA —
    // myös käyttäjän ENSIMMÄISELLÄ kirjautumisella, jolloin profiilirivia ei
    // vielä ole. Aiemmin premium kirjoitettiin vain jos profiili oli jo
    // olemassa, joten uudet premium-tekijät jäivät is_premium=false.
    const profileUpdate: Record<string, unknown> = {
      user_id: userId,
      wp_user_id,
      wp_post_id: wp_post_id ?? null,
      is_premium: is_premium === true,
    }
    if (name)         profileUpdate.name = name
    if (age != null)  profileUpdate.age  = age
    if (city != null) profileUpdate.city = city
    if (bio != null)  profileUpdate.bio  = bio

    // Upsert profiilirivin user_id:n perusteella → luo jos puuttuu, päivitä jos on.
    // Vaatii uniikin rajoitteen profiles.user_id:lle (yleensä on).
    const { error: upsertError } = await admin
      .from('profiles')
      .upsert(profileUpdate as never, { onConflict: 'user_id' })

    if (upsertError) {
      throw new Error(`Profile upsert failed: ${upsertError.message}`)
    }

    // ── 5. Redirect to auth callback with magic link token ────────────────
    const hashed = linkData.properties?.hashed_token
    if (!hashed) throw new Error('No hashed_token in link response')

    const callbackUrl = new URL('/auth/callback', origin)
    callbackUrl.searchParams.set('token_hash', hashed)
    callbackUrl.searchParams.set('type', 'magiclink')

    return NextResponse.redirect(callbackUrl)
  } catch (err) {
    console.error('WP SSO error:', err instanceof Error ? err.message : err)
    loginUrl.searchParams.set('error', 'sso_failed')
    return NextResponse.redirect(loginUrl)
  }
}
